tasks:
  - name: bootstrap
    init: |
      npm install -g bats tap
      sudo ln -s "$(which bats)" /usr/local/bin/bats
      sudo ln -s "$(which node)" /usr/local/bin/node
      sudo ln -s "$(which tap)" /usr/local/bin/tap
      # Run last because the command below does "command detection" and we don't
      # necessarily want to install `node-tap` when `tap` is already installed.
      sudo add-apt-repository -y ppa:canonical-server/server-backports
      sudo make apt_install
      # For MicroVM:
      make -C extras/microvm kernel
      sudo make -C extras/microvm virtiofsd install_kernel

    before: |
      # This is needed to hide a warning in `sudo make install`.
      sudo git config --global --add safe.directory "$GITPOD_REPO_ROOT"

      echo 'YACR_ROOT_DIR=/tmp/yacr' | sudo tee -a /etc/environment
      echo 'YACS_ROOT_DIR=/tmp/yacs' | sudo tee -a /etc/environment
      echo 'YAMAN_ROOT_DIR=/tmp/yaman' | sudo tee -a /etc/environment

      mkdir -p ~/.run
      chmod 700 ~/.run
      echo 'export XDG_RUNTIME_DIR=~/.run' >> ~/.bashrc.d/100-containers

      source ~/.bashrc.d/100-containers

      # Build and install the different tools
      make all && sudo make install && sudo make install_completion
      source /usr/share/bash-completion/bash_completion
