tasks:
  - name: bootstrap
    before: |
      # This is needed to hide a warning in `sudo make install`.
      sudo git config --global --add safe.directory "$GITPOD_REPO_ROOT"

      echo 'YAMAN_ROOT_DIR=/tmp/yaman' | sudo tee -a /etc/environment

      mkdir -p ~/.run
      chmod 700 ~/.run
      echo 'export XDG_RUNTIME_DIR=~/.run' >> ~/.bashrc.d/100-containers

      source ~/.bashrc.d/100-containers

      # Build and install the different tools
      make all && sudo make install && sudo make install_completion
      source /usr/share/bash-completion/bash_completion
