name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup BATS testing framework
      uses: mig4/setup-bats@v1.2.0
      with:
          bats-version: 1.7.0

    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install dependencies
      run: |
        sudo make apt_install

    - name: Build and install
      run: |
        make all
        sudo make install

    - name: Run tests
      run: |
        go test ./...
        go vet ./...

    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "latest"
        install-go: false

    - name: Run integration tests
      run: |
        mkdir -p ~/.run/yacr
        mkdir -p ~/.run/yacs
        mkdir -p ~/.run/yaman

        export YACR_ROOT_DIR=~/.run/yacr
        export YACS_ROOT_DIR=~/.run/yacs
        export YAMAN_ROOT_DIR=~/.run/yaman

        make alpine_bundle > /dev/null

        bats tests/integration/yacs/ tests/integration/yaman/
